- name: Build Artifact ROOT.war & SQL file to be copied in files/ directory
  import_playbook: build.yaml

- name: Set Hosts to Ip Mapping in /etc/hosts file of all servers
  import_playbook: set_hosot_ip_map.yaml

- name: Setup dbserver
  import_playbook: db.yaml

- name: Deploy SQL file on dbserver
  import_playbook: dbdeploy.yaml

- name: Setup memcached service
  import_playbook: memcache.yaml

- name: Setup rabbitmq service 
  import_playbook: appserver.yaml

- name: Setup tomccat application server
  import_playbook: appserver.yaml

- name: Setup Nginx webserver
  import_playbook: web.yaml
  